# Generated by Django 3.0.3 on 2020-02-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=15)),
                ('student_address', models.CharField(max_length=20)),
                ('student_hobbies', models.CharField(max_length=15)),
            ],
        ),
    ]
